baseURL = 'https://vulcalien.net/'
title = "Vulcalien's website"
copyright = 'Copyright 2023 Vulcalien'

languageCode = 'en'

theme = 'PaperMod'

[markup.goldmark.renderer]
    unsafe = true

[params]
    mainSections = ['blog', 'projects']

[menu]
    [[menu.main]]
        name = 'Home'
        pageref = '/'
        weight = 1
    [[menu.main]]
        name = 'Blog'
        pageref = '/blog'
        weight = 2
    [[menu.main]]
        name = 'Projects'
        pageref = '/projects'
        weight = 3
    [[menu.main]]
        name = 'Contact'
        pageref = '/contact'
        weight = 4
    [[menu.main]]
        name = 'GitHub'
        url = 'https://github.com/Vulcalien'
        weight = 5
